"""Impact report: grounded summary, confirmed sliders, timeline, evidence table, HTML download."""
import streamlit as st
from streamlit_image_comparison import image_comparison

from gt import config, db, media, report
from gt.ui import AI_BADGE, next_step, page_header, page_setup

page_setup("Impact report", ":material/description:")
page_header("Step 4 of 4 · Share", "Impact report",
            "A shareable summary built only from confirmed pairs, with every claim linked to its photo.",
            ["Pick a scope: all projects or one.", "Check the summary and the trust checks next to it.",
             "Download the HTML report. Open it and use Print → Save as PDF for a PDF."])

projects = {report.ALL: "All projects"} | {p["id"]: p["name"] for p in db.projects()}
top_l, top_r = st.columns([3, 2], vertical_alignment="bottom")
scope = top_l.selectbox("Report scope", list(projects), format_func=projects.get, key="report_scope")
f = report.facts(scope)
if not f["image_count"]:
    st.warning("No evidence in this scope.")
    st.stop()
assets = db.assets(None if scope == report.ALL else scope)

summary, is_ai = report.cached_summary(scope), True
can_generate = config.ai_ready() and not config.DEMO_MODE
if can_generate and st.session_state.pop("regen_summary", False):
    with st.spinner("Summarizing stored captions, tags, dates and confirmed pairs…"):
        summary = report.generate_summary(scope)
        report.save_summary(summary)
if not summary:
    summary, is_ai = {"text": report.template_summary(f)}, False

html_doc = report.to_html(projects[scope], f, summary, is_ai, assets)
with top_r:
    st.download_button("Download report (HTML)", html_doc, file_name=f"ground-truth-report-{scope}.html",
                       mime="text/html", type="primary", icon=":material/download:", width="stretch")
    st.caption("Need a PDF? Open the file, then Print → Save as PDF.")

c1, c2, c3 = st.columns(3)
c1.metric("Images", f["image_count"], border=True)
c2.metric("Confirmed before/after pairs", len(f["confirmed_pairs"]), border=True)
c3.metric("Date range", " → ".join(f["date_range"]) if f["date_range"] else "n/a", border=True)
st.caption("Counted directly from the data, not generated by AI.")

by_id = {a["id"]: a for a in assets}
tab_sum, tab_pairs, tab_time, tab_table = st.tabs(
    ["Summary", f"Before & after ({len(f['confirmed_pairs'])})", "Timeline", "Evidence table"])

with tab_sum:
    left, right = st.columns([3, 2])
    with left:
        if is_ai:
            st.badge(f"AI-generated · {summary.get('model')}", icon=":material/auto_awesome:", color="violet")
            st.caption(f"{AI_BADGE} · {summary.get('generated_at')}")
        else:
            st.badge("Template summary (no AI in demo)" if config.DEMO_MODE else "Template summary (no AI)", color="gray")
        if can_generate and st.button("Regenerate summary" if summary and is_ai else "Generate summary from stored facts",
                                      icon=":material/refresh:"):
            st.session_state.regen_summary = True
            st.rerun()
        st.markdown(report.strip_disclaimer(summary["text"]))
        if report.disclaimer():
            st.caption(report.SHORT_NOTE)
        with st.expander("Facts given to the model"):
            st.json(f, expanded=False)
    with right:
        st.markdown("**Trust checks**")
        if is_ai and summary.get("facts_hash") != report.facts_hash(f):
            st.warning("The underlying data changed since this summary was generated.")
        if summary.get("citation_issues"):
            st.error("This AI summary cites asset ids that do not exist in the evidence: "
                     + ", ".join(f"`{i}`" for i in summary["citation_issues"]) + ". Treat those sentences as unreliable.")
        else:
            st.success("Every asset id cited in this summary exists in the evidence table.")
        st.success("Written only from the facts: stored captions, tags, dates and confirmed pairs.")
        st.info("Before/after pairs show **visible difference between confirmed paired images**. "
                "They do not verify an environmental outcome.", icon=":material/info:")

with tab_pairs:
    if not f["confirmed_pairs"]:
        st.info("No confirmed pairs in this scope yet.")
        st.page_link("views/3_Pairs.py", label="Review pairs", icon=":material/compare:")
    for row in [f["confirmed_pairs"][i:i + 2] for i in range(0, len(f["confirmed_pairs"]), 2)]:
        for col, p in zip(st.columns(2), row):
            b, a = by_id[p["before"]["id"]], by_id[p["after"]["id"]]
            blur = bool(b.get("people_present") or a.get("people_present"))
            with col:
                st.markdown(f"**{b.get('project_name')}** · {p['before']['date'] or '?'} → {p['after']['date'] or '?'}  \n"
                            f"`{b['id']}` → `{a['id']}`")
                try:
                    image_comparison(img1=media.url_for(b, "compare", blur), img2=media.url_for(a, "compare", blur),
                                     label1="Before", label2="After", width=520, in_memory=True)
                except Exception as ex:
                    st.error(f"Could not load comparison images ({type(ex).__name__}).")
    if config.DEMO_MODE:
        st.caption("Pairs you confirm on Review pairs in demo mode are session-only and are not added to this report.")

with tab_time:
    for a in sorted(assets, key=lambda x: x.get("captured_at") or "9999"):
        role = (a.get("role") or "").title()
        st.markdown(f"**{(a.get('captured_at') or 'undated')[:10]}**  \n"
                    f"{role + ' · ' if role else ''}{a.get('project_name')} · `{a['id']}`")
        st.caption(a.get("caption") or "no caption")

with tab_table:
    st.dataframe(report.evidence_rows(assets), hide_index=True, width="stretch",
                 column_config={"original": st.column_config.LinkColumn("source (original)")})

next_step("Check a claim", "Trace any photo in the report back to its source.", "Trace an image", "views/5_Trace.py")
