"""Impact report: grounded summary, timeline, confirmed sliders, evidence table, HTML download."""
import streamlit as st
import streamlit.components.v1 as components
from streamlit_image_comparison import image_comparison

from gt import config, db, media, report
from gt.ui import AI_BADGE, SYNTHETIC_NOTE, any_synthetic, page_setup, synthetic_badge

page_setup("Report", "📄")
st.title("📄 Impact report")

projects = {report.ALL: "All projects"} | {p["id"]: p["name"] for p in db.projects()}
scope = st.selectbox("Scope", list(projects), format_func=projects.get)
f = report.facts(scope)
if not f["image_count"]:
    st.warning("No evidence in this scope.")
    st.stop()
assets = db.assets(None if scope == report.ALL else scope)

if any_synthetic(assets):
    st.warning(SYNTHETIC_NOTE + " This report demonstrates the reporting workflow only.", icon="🧪")

c1, c2, c3 = st.columns(3)
c1.metric("Images", f["image_count"])
c2.metric("Confirmed before/after pairs", len(f["confirmed_pairs"]))
c3.metric("Date range", " → ".join(f["date_range"]) if f["date_range"] else "n/a")
st.caption("These numbers are counted from stored data, not generated by AI.")

# --- summary ------------------------------------------------------------------------
st.subheader("Summary")
summary, is_ai = report.cached_summary(scope), True
if summary and summary.get("facts_hash") != report.facts_hash(f):
    st.caption("⚠️ The underlying data changed since this summary was generated.")
if config.ai_ready() and not config.DEMO_MODE:
    if st.button("✨ Generate summary from stored facts" if not summary else "✨ Regenerate summary"):
        with st.spinner("Summarizing stored captions, tags, dates and confirmed pairs…"):
            summary = report.generate_summary(scope)
            report.save_summary(summary)
if not summary:
    summary, is_ai = {"text": report.template_summary(f)}, False
if is_ai:
    st.caption(f"{AI_BADGE} · generated only from stored captions, tags, dates and confirmed pairs · "
               f"`{summary.get('model')}` · {summary.get('generated_at')}")
else:
    st.caption("Template summary (no AI). " + ("A cached AI summary is not available for this scope." if config.DEMO_MODE else ""))
st.markdown(summary["text"])
with st.expander("Facts given to the model (the only allowed source)"):
    st.json(f, expanded=False)
st.info("Before/after pairs show **visible difference between confirmed paired images**. "
        "They do not verify an environmental outcome.", icon="ℹ️")

# --- confirmed pairs ------------------------------------------------------------------
st.subheader("Confirmed before/after pairs")
by_id = {a["id"]: a for a in assets}
if not f["confirmed_pairs"]:
    st.caption("No confirmed pairs in this scope.")
for p in f["confirmed_pairs"]:
    b, a = by_id[p["before"]["id"]], by_id[p["after"]["id"]]
    blur = bool(b.get("people_present") or a.get("people_present"))
    synthetic_badge(b, a)
    st.markdown(f"**{b.get('project_name')}** · {p['before']['date'] or '?'} → {p['after']['date'] or '?'} · "
                f"`{b['id']}` → `{a['id']}`")
    try:
        image_comparison(img1=media.url_for(b, "compare", blur), img2=media.url_for(a, "compare", blur),
                         label1="Before", label2="After", width=760, in_memory=True)
    except Exception as ex:
        st.error(f"Could not load comparison images ({type(ex).__name__}).")
if config.DEMO_MODE:
    st.caption("Pairs you confirm on the Pairs page in demo mode are session-only and are not added to this report.")

# --- timeline ------------------------------------------------------------------------
st.subheader("Timeline")
for a in sorted(assets, key=lambda x: x.get("captured_at") or "9999"):
    st.markdown(f"- **{(a.get('captured_at') or 'undated')[:10]}** · {a.get('project_name')} · "
                f"{(a.get('activity_type') or 'unclassified').replace('_', ' ')} · `{a['id']}` — "
                f"*{a.get('caption') or 'no caption'}*")

# --- evidence table ------------------------------------------------------------------
st.subheader("Evidence table")
st.dataframe(report.evidence_rows(assets), hide_index=True, width="stretch",
             column_config={"original": st.column_config.LinkColumn("source (original)")})

# --- export --------------------------------------------------------------------------
html_doc = report.to_html(projects[scope], f, summary, is_ai, assets)
st.download_button("⬇️ Download report (HTML, print-friendly)", html_doc,
                   file_name=f"ground-truth-report-{scope}.html", mime="text/html", type="primary")
st.caption("Open the downloaded file and use *Print → Save as PDF* for a PDF copy.")
with st.expander("Print preview"):
    components.html(html_doc, height=700, scrolling=True)  # iframe keeps report CSS isolated
